function input_dialog % Manages the dialog window
clear all
close all
format long

fig_input = figure('Name','Input dialog','Position',[1250,300,560,420]);
txt_NC = uicontrol('Style',...
    'text',...
    'String','# of cells (NC)',...
    'HorizontalAlignment','center',...
    'Position',[10 380 100 20],...
    'Visible','on',...
    'Enable','on');

edit_NC = uicontrol('Style',...
    'edit',...
    'String','100',...
    'HorizontalAlignment','center',...
    'Position',[10 360 100 20],...
    'Visible','on',...
    'Enable','on');

txt_tit2 = uicontrol('Style',...
    'text',...
    'String','CFL',...
    'HorizontalAlignment','center',...
    'Position',[10 330 100 20],...
    'Visible','on',...
    'Enable','on');

edit_CFL = uicontrol('Style',...
    'edit',...
    'String','0.8',...
    'HorizontalAlignment','center',...
    'Position',[10 310 100 20],...
    'Visible','on',...
    'Enable','on');

txt_tit3 = uicontrol('Style',...
    'text',...
    'String','Accuracy (IORD)',...
    'HorizontalAlignment','center',...
    'Position',[10 280 100 20],...
    'Visible','on',...
    'Enable','on');

edit_IORD = uicontrol('Style',...
    'edit',...
    'String','1',...
    'HorizontalAlignment','center',...
    'Position',[10 260 100 20],...
    'Visible','on',...
    'Enable','on');

txt_tit4 = uicontrol('Style',...
    'text',...
    'String','Convective scheme',...
    'HorizontalAlignment','center',...
    'Position',[10 230 100 20],...
    'Visible','on',...
    'Enable','on');
bg_isch = uicontrol('Style',...
    'popup',...
    'String',{'FDS-Osher','FDS-Osher (O-ordering)', 'FDS-Osher (P-ordering)'},... % you can add other stings ...
    'Position',[10 210 100 20],...
    'Visible','on',...
    'Enable','on');

pop_test = uicontrol('Style',...
    'popup',...
    'String',{'Generic RP','Sod shock tube','Test #1 Toro book','Test #2 Toro book','Test #3 Toro book','Test #4 Toro book','Test #5 Toro book','Test #6 Toro book','Test #7 Toro book','Test #8 Toro book'},...
    'CallBack',@test_cbk,...
    'Position',[220 380 120 20],...
    'Visible','on',...
    'Enable','on');

    function test_cbk(source,event_stretch)
        if (pop_test.Value ==2)
            edit_rhoL.String = '8.0';
            edit_uL.String = '0.0';
            edit_pL.String = '10.0';
            edit_rhoR.String = '1.0';
            edit_uR.String = '0.0';
            edit_pR.String = '1.0';
            edit_timemax.String = '0.14385';
            nc = str2double(edit_NC.String);
            ka    = 0.35*nc+1;      %default value
            kk=sprintf('%.0f',ka);
            edit_ka.String = kk;
  
        elseif (pop_test.Value ==3)
            edit_rhoL.String = '1.0';
            edit_uL.String = '0.75';
            edit_pL.String = '1.0';            
            edit_rhoR.String = '0.125';
            edit_uR.String = '0.0';
            edit_pR.String = '0.1';
            edit_timemax.String = '.2';                   
            edit_x0.String = '0.3';                   
            edit_ka.String = '1000000000';

        elseif (pop_test.Value ==4)
            edit_rhoL.String = '1.0';
            edit_uL.String = '-2.0';
            edit_pL.String = '0.4';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '2.0';
            edit_pR.String = '0.4';
            edit_timemax.String = '0.15';
            edit_x0.String = '0.5';                   
            edit_ka.String = '1000000000';
                        
        elseif (pop_test.Value ==5)
            edit_rhoL.String = '1.0';
            edit_uL.String = '0.0';
            edit_pL.String = '1000.0';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '0.0';
            edit_pR.String = '0.01';
            edit_timemax.String = '0.012';
            edit_x0.String = '0.5';                   
            edit_ka.String = '1000000000';
            
        elseif (pop_test.Value ==6)
            edit_rhoL.String = '5.99924';
            edit_uL.String = '19.5975';
            edit_pL.String = '460.894';            
            edit_rhoR.String = '5.99242';
            edit_uR.String = '-6.19633';
            edit_pR.String = '46.0950';
            edit_timemax.String = '0.035';
            edit_x0.String = '0.4';                   
            edit_ka.String = '1000000000';

        elseif (pop_test.Value ==7)
            edit_rhoL.String = '1.0';
            edit_uL.String = '-19.59745';
            edit_pL.String = '1000.0';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '-19.59745';
            edit_pR.String = '0.01';
            edit_timemax.String = '0.012';
            edit_x0.String = '0.8';                   
            edit_ka.String = '1000000000';
            
        elseif (pop_test.Value ==8)
            edit_rhoL.String = '1.0';
            edit_uL.String = '2.0';
            edit_pL.String = '0.1';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '-2.0';
            edit_pR.String = '0.1';
            edit_timemax.String = '0.8';
            edit_x0.String = '0.5';                   
            edit_ka.String = '1000000000';

        elseif (pop_test.Value ==9)
            edit_rhoL.String = '1.4';
            edit_uL.String = '0.0';
            edit_pL.String = '1.0';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '0.0';
            edit_pR.String = '1.0';
            edit_timemax.String = '2.0';
            edit_x0.String = '0.5';                   
            edit_ka.String = '1000000000';

        elseif (pop_test.Value ==10)
            edit_rhoL.String = '1.4';
            edit_uL.String = '0.1';
            edit_pL.String = '1.0';            
            edit_rhoR.String = '1.0';
            edit_uR.String = '0.1';
            edit_pR.String = '1.0';
            edit_timemax.String = '2.0';
            edit_x0.String = '0.5';                   
            edit_ka.String = '1000000000';
            
        elseif (pop_test.Value ==1)
            edit_rhoL.String = '1.0';
            edit_uL.String = '0.75';
            edit_pL.String = '1.0';            
            edit_rhoR.String = '0.125';
            edit_uR.String = '0.0';
            edit_pR.String = '0.1';
            edit_timemax.String = '100000.0';       
        end
    end

%    function bselection(source,event_bs,handles_bs)
%        if (event_bs.NewValue.String == 'Left ')
%            handles_bs.str_side = 'Left ';
%            edit_dxmin_l.Visible = 'on';
%            edit_dxmin_l.Enable  = 'on';
%            edit_dxmin_l.Value  = 1;
%            edit_dxmin_r.Visible = 'off';
%            edit_dxmin_r.Enable  = 'off';
%            edit_dxmin_r.Value  = 0;
%        else
%            handles_bs.str_side = 'Right';
%            edit_dxmin_r.Visible = 'on';
%            edit_dxmin_r.Enable  = 'on';
%            edit_dxmin_r.Value  = 1;
%            edit_dxmin_l.Visible = 'off';
%            edit_dxmin_l.Enable  = 'off';
%            edit_dxmin_l.Value  = 0;
%        end
%    end


txt_titL_param = uicontrol('Style',...
    'text',...
    'String','Left side',...
    'HorizontalAlignment','center',...
    'Position',[220 350 120 20],...
    'Visible','on',...
    'Enable','on');

txt_rhoL = uicontrol('Style',...
    'text',...
    'String','rho_L',...
    'HorizontalAlignment','left',...
    'Position',[200 325 100 20],...
    'Visible','on',...
    'Enable','on');

edit_rhoL = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[250 327 100 20],...
    'Visible','on',...
    'Enable','on');

txt_uL = uicontrol('Style',...
    'text',...
    'String','u_L',...
    'HorizontalAlignment','left',...
    'Position',[200 295 100 20],...
    'Visible','on',...
    'Enable','on');

edit_uL = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[250 297 100 20],...
    'Visible','on',...
    'Enable','on');

txt_pL = uicontrol('Style',...
    'text',...
    'String','p_L',...
    'HorizontalAlignment','left',...
    'Position',[200 265 100 20],...
    'Visible','on',...
    'Enable','on');

edit_pL = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[250 267 100 20],...
    'Visible','on',...
    'Enable','on');

txt_Gamma = uicontrol('Style',...
    'text',...
    'String','Gamma',...
    'HorizontalAlignment','left',...
    'Position',[200 235 100 20],...
    'Visible','on',...
    'Enable','on');

edit_Gamma = uicontrol('Style',...
    'edit',...
    'String','1.4',...
    'HorizontalAlignment','left',...
    'Position',[250 237 100 20],...
    'Visible','on',...
    'Enable','on');

txt_titR_param = uicontrol('Style',...
    'text',...
    'String','Right side',...
    'HorizontalAlignment','center',...
    'Position',[420 350 120 20],...
    'Visible','on',...
    'Enable','on');

txt_rhoR = uicontrol('Style',...
    'text',...
    'String','rho_R',...
    'HorizontalAlignment','left',...
    'Position',[380 325 100 20],...
    'Visible','on',...
    'Enable','on');

edit_rhoR = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[430 327 100 20],...
    'Visible','on',...
    'Enable','on');

txt_uR = uicontrol('Style',...
    'text',...
    'String','u_R',...
    'HorizontalAlignment','left',...
    'Position',[380 295 100 20],...
    'Visible','on',...
    'Enable','on');

edit_uR = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[430 297 100 20],...
    'Visible','on',...
    'Enable','on');

txt_pR = uicontrol('Style',...
    'text',...
    'String','p_R',...
    'HorizontalAlignment','left',...
    'Position',[380 265 100 20],...
    'Visible','on',...
    'Enable','on');

edit_pR = uicontrol('Style',...
    'edit',...
    'String','1.0',...
    'HorizontalAlignment','left',...
    'Position',[430 267 100 20],...
    'Visible','on',...
    'Enable','on');

txt_x0 = uicontrol('Style',...
    'text',...
    'String','x0',...
    'HorizontalAlignment','left',...
    'Position',[380 235 100 20],...
    'Visible','on',...
    'Enable','on');

edit_x0 = uicontrol('Style',...
    'edit',...
    'String','0.5',...
    'HorizontalAlignment','left',...
    'Position',[430 237 100 20],...
    'Visible','on',...
    'Enable','on');

txt_timemax = uicontrol('Style',...
    'text',...
    'String','time_max',...
    'HorizontalAlignment','left',...
    'Position',[200 205 100 20],...
    'Visible','on',...
    'Enable','on');

edit_timemax = uicontrol('Style',...
    'edit',...
    'String','0.00',...
    'HorizontalAlignment','left',...
    'Position',[250 207 100 20],...
    'Visible','on',...
    'Enable','on');

txt_ka = uicontrol('Style',...
    'text',...
    'String','iterations',...
    'HorizontalAlignment','left',...
    'Position',[200 175 100 20],...
    'Visible','on',...
    'Enable','on');

edit_ka = uicontrol('Style',...
    'edit',...
    'String','0',...
    'HorizontalAlignment','left',...
    'Position',[250 177 100 20],...
    'Visible','on',...
    'Enable','on');

txt_stepcounter = uicontrol('Style',...
    'text',...
    'String','step K:',...
    'HorizontalAlignment','left',...
    'Position',[10 100 100 20],...
    'Visible','on',...
    'Enable','on');

txt_stepcounter2 = uicontrol('Style',...
    'text',...
    'String','0.00',...
    'HorizontalAlignment','left',...
    'Position',[50 100 50 20],...
    'CallBack',@pb_cbk,...  
    'Visible','on',...
    'Enable','on');

txt_time = uicontrol('Style',...
    'text',...
    'String','time:',...
    'HorizontalAlignment','left',...
    'Position',[10 70 100 20],...
    'Visible','on',...
    'Enable','on');

txt_time2 = uicontrol('Style',...
    'text',...
    'String','0.0000',...
    'HorizontalAlignment','left',...
    'Position',[50 70 50 20],...
    'CallBack',@pb_cbk,...  
    'Visible','on',...
    'Enable','on');

pb = uicontrol('Style','pushbutton',...
    'String','Start',...
    'Position',[10 120 100 30],...
    'CallBack',@pb_cbk,...
    'Enable','on');

pb_cont = uicontrol('Style','pushbutton',...
    'String','Continue',...
    'Position',[210 120 100 30],...
    'CallBack',@pb_cbk,...
    'Enable','off');

pb_stop = uicontrol('Style','pushbutton',...
    'String','Stop',...
    'Position',[430 120 100 30],...
    'CallBack',@pb_stop_cbk,...
    'Enable','off');

fig_rho = figure('Name','Density','Position',[50,50,560,420]);
fig_pre = figure('Name','Pressure','Position',[650,50,560,420]);
fig_vel = figure('Name','Velocity','Position',[1250,50,560,420]);
fig_tem = figure('Name','Temperature','Position',[650,300,560,420]);


    function pb_cbk(source,event,handles)
        pb.Enable = 'off';
        Euler_1D(pb_cont,pb_stop,fig_rho,fig_pre,fig_vel,fig_tem,bg_isch,pop_test,edit_NC,edit_CFL,edit_IORD,edit_rhoL,edit_uL,edit_pL,edit_Gamma,edit_rhoR,edit_uR,edit_pR,edit_x0,edit_timemax,edit_ka,txt_stepcounter2,txt_time2);
    end

    function pb_stop_cbk(source1,event1,handles1)
        pb_cont.Enable = 'off'
        pb_stop.Enable = 'off';
    end
end

% Takes input data and solves the Euler equations 
function Euler_1D(pb_cont,pb_stop,fig_rho,fig_pre,fig_vel,fig_tem,bg_isch,pop_test,edit_NC,edit_CFL,edit_IORD,edit_rhoL,edit_uL,edit_pL,edit_Gamma,edit_rhoR,edit_uR,edit_pR,edit_x0,edit_timemax,edit_ka,txt_stepcounter2,txt_time2) %(1D and quasi-1D Euler equations)

% Transforming input variables into numbers

%C       (perfect gas (gamma=1.4), primitive variables P,U,H)

global gamma ga gb gc gd ge gf gg gh gi gj % era USE PIGAMMA_PAR
global nc ncm k kout ka iord itest stab  % era USE NUM_PAR
global b c diverg c1 c2 x0 dx            %        era USE GEOM_PAR
global x                                          % era USE GEOM_VAR
global   time dt dtodx dtitest4 timemax timek    % era USE TIME_PAR
global p t u s rho a e amach ptot ttot flow flht h htot % era USE VARS
global w1 w2 w3 f1 f2 f3 phi1 phi2 phi3                    % era USE VARS
global p t u s rho a e amach ptot ttot flow flht h htot % era USE VARS
global w1 w2 w3 f1 f2 f3 phi1 phi2 phi3                    % era USE VARS
%        USE BC
global nrt rtrms rtmax                    % era USE CONVERG
global  xsh10 xsh20 p1 rho1 u1 p2 rho2 u2 p3 rho3 u3 p4 rho4 u4 % era USE INIT_PAR
global  vsh1 vsh2 vsh3 vsh4 vsh5 vsh3l vsh3r vsh4l vsh4r % era USE INIT_PAR
global  xsh1 xsh2 xsh3 xsh4 xsh5 xsh3l xsh3r xsh4l xsh4r % era USE INIT_PAR
global pth tth uth sth rhoth ath eth amachth  ttotth flowth flhtth hth % era USE THEORETICAL
global htotth r1th r2th r3th fplotth xth % era USE THEORETICAL
global xshth fthshu fthshd pu pd rhou tu su sd uu ud amu amd % era USE THEORETICAL
global htotu htotd flowu flowd flhtu flhtd r1u r1d r2u r2d r3u r3d % era USE THEORETICAL
global x1 x2 x3 x4 x5 % era USE THEORETICAL
global p1l p1r u1l u1r s1l s1r a1l a1r t1l t1r rho1l rho1r e1l e1r % era USE THEORETICAL
global p2l p2r u2l u2r s2l s2r a2l a2r t2l t2r rho2l rho2r e2l e2r % era USE THEORETICAL
global p3l p3r u3l u3r s3l s3r a3l a3r t3l t3r rho3l rho3r e3l e3r % era USE THEORETICAL
global p4l p4r u4l u4r s4l s4r a4l a4r t4l t4r rho4l rho4r e4l e4r % era USE THEORETICAL

if (pb_cont.Value == 0)

% Taking values from the input window 
nc = str2double(edit_NC.String);
iord = str2double(edit_IORD.String);
stab = str2double(edit_CFL.String);
ischeme = bg_isch.Value; % 1-> PFD-Osher
gamma = str2double(edit_Gamma.String);
rhol = str2double(edit_rhoL.String);
ul   = str2double(edit_uL.String);
pl   = str2double(edit_pL.String); 
rhor = str2double(edit_rhoR.String);
ur   = str2double(edit_uR.String);
pr   = str2double(edit_pR.String);
x0   = str2double(edit_x0.String);

fprintf('Euler_1D (FDS - 1st and 2nd Order)')
k=1; % Time counter
time=0.0;
timek(k)=time;

if (pop_test.Value)==1
    itest = 2;
    ka = str2double(edit_ka.String);  % ka = numero totale di passi temporali
    timemax = str2double(edit_timemax.String); % timemax = tempo massimo di integrazione
elseif (pop_test.Value)==2
    itest = 1;
elseif (pop_test.Value)>=3
    itest = pop_test.Value;
    ka = str2double(edit_ka.String);
    timemax = str2double(edit_timemax.String);    
end

% Defines the grid with BC
init(rhol,ul,pl,rhor,ur,pr); % see init.m

kk=sprintf('%.0f',ka);
edit_ka.String = kk;     

% Computes exact solution
[utha,uthb,uthc,uthd,ptha,pthb,pthc,pthd,atha,athb,athc,athd,rhotha,rhothb,rhothc,rhothd,stha,sthb,sthc,sthd,alama,alamb,alamc,alamd,alamx,vshl,vshr,el,er] = rpsolver();

kk=sprintf('%.0f',k);
txt_stepcounter2.String = kk;    

tt=sprintf('%.6f',time);
%idx=regexp(tt,'0+','start');
%tt(idx(end):end)=[];
txt_time2.String = tt;    

%  plot the initial conditions
figure(fig_rho)
plot(x,rho,'o-')
figure(fig_pre)
plot(x,p,'o-')
figure(fig_vel)
plot(x,u,'o-')
figure(fig_tem)
plot(x,t,'o-')
end

if (pb_cont.Value == 1)
    ka = str2double(edit_ka.String);
    if (pop_test.Value == 2)
        timemax = dt*(ka-1);
        tt=sprintf('%.6f',timemax);
        edit_timemax.String = tt;
    else
        timemax= str2double(edit_timemax.String);
        stab= str2double(edit_CFL.String);

    end
    [utha,uthb,uthc,uthd,ptha,pthb,pthc,pthd,atha,athb,athc,athd,rhotha,rhothb,rhothc,rhothd,stha,sthb,sthc,sthd,alama,alamb,alamc,alamd,alamx,vshl,vshr,el,er] = rpsolver();
end

while (k < ka) && (time < timemax)
    k=k+1;
    fprintf('K =%i - TIME=%f',k,time)
    
    dt=1.e5;
    dtd(2:ncm) = dx./(abs(u(2:ncm))+a(2:ncm)); % delta t = delta x / max(|lambda_i|) -> |u|+a, may vary from cell to cell
    dt = min(dtd(2:ncm)); % defining a global time steps for all cells
    
    if itest == 1
        dt = dtodx * dx;
    elseif itest >=2
        dt=dt*stab;
    end
    time = time+dt;
    timek(k) = time;

kk=sprintf('%.0f',k);
txt_stepcounter2.String = kk;    

tt=sprintf('%.6f',time);
txt_time2.String = tt;    
    
    if (iord == 2)  % 
        eno1() % Computing slopes of variables and time derivative inside the cell for the 2nd order
    end    
    split(); % Different splitting -> approximate Riemann's problem
    march(); % Advancing in time
    
    if (itest == 1)
        sum1=mean(w1);
        sum2=mean(w2) + (p(nc)-p(1))*time;
        sum3=mean(w3);
        
        fprintf('K=%i - sum1=%f - sum2=%f - sum3=%f',k,sum1,sum2,sum3);
    end

% Plotting
figure(fig_rho)
hold off
plot(x,rho,'o-')
hold on

figure(fig_pre)
hold off
plot(x,p,'o-')
hold on

figure(fig_vel)
hold off
plot(x,u,'o-')
hold on

figure(fig_tem)
hold off
plot(x,t,'o-')
hold on

    %      CALL GNUPLOT
    %       costruire routine per output dati e visualizzazione

% Evaluate theoretical solution and plot
thesol(timek(k),utha,uthb,uthc,uthd,ptha,pthb,pthc,pthd,atha,athb,athc,athd,rhotha,rhothb,rhothc,rhothd,stha,sthb,sthc,sthd,alama,alamb,alamc,alamd,alamx,vshl,vshr,el,er);
figure(fig_rho)
plot(xth,rhoth,'o-')

figure(fig_pre)
plot(xth,pth,'o-')

figure(fig_vel)
plot(xth,uth,'o-')

figure(fig_tem)
plot(xth,pth./rhoth,'o-')
end

pb_cont.Enable = 'On';
pb_stop.Enable = 'On';
edit_ka.String = '(increase or stop)';

%if (pb_stop.Value) == 1
%    return
%end

end


% Summing up.
% First order -> split computes fluxes and advances in time
% Second order -> some changes then split


% For the exam
% Begin with the first order, then modify eventually
% Split and march could be modified
% Primitives variables may be different.
%   Whatever it is, evaluate in j, j+1
% See the manual of this code